# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bioRxivScraper": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://JohnGiorgi.github.io/biorxiv_scraper/"

git_url = "https://github.com/fastai/biorxiv_scraper/tree/master/"

def custom_doc_links(name): return None